version: "3"
services:
  backend:
    container_name: backend
    build: .
    image: backend
    networks:
       int222:
          ipv4_address: 172.10.0.3
    environment:
      - MYSQL_DATABASE=ProductCase
      - MYSQL_USER=test221
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - ~/imagestorage:/product-images

networks:
  default:
    external:
      name: int221_network